using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WPF_INSTALL_APP
{
    internal class PackageList
    {
        public List<String> Package = new List<String>{
            "winget install --id=Zoom.Zoom -e",                        
            "winget install --id=Discord.Discord -e",
            "winget install --id=Telegram.TelegramDesktop -e",
            "winget install --id=RadolynLabs.AyuGramDesktop -e",
            "winget install --id=TeamSpeakSystems.TeamSpeakClient -e",
            "winget install --id=Google.Chrome -e",
            "winget install --id=Mozilla.Firefox -e",
            "winget install --id=Opera.Opera -e",
            "winget install --id=Opera.OperaGX -e",
            "winget install --id=Yandex.Browser -e",
            "winget install --id=DuckDuckGo.DesktopBrowser -e",
            "winget install --id=Brave.Brave -e",
            "winget install --id=Vivaldi.Vivaldi -e",
            "winget install --id=Waterfox.Waterfox -e",
            "winget install --id=LibreWolf.LibreWolf -e",
            "winget install --id=Notepad++.Notepad++ -e",
            "winget install --id=Microsoft.VisualStudioCode -e",
            "winget install --id=GitHub.Atom -e",
            "winget install --id=appmakes.Typora -e",
            "winget install --id=Automattic.Simplenote -e",
            "winget install --id=TheDocumentFoundation.LibreOffice -e",
            "winget install --id=Spotify.Spotify -e",
            "winget install --id=VideoLAN.VLC -e",
            "winget install --id=Yandex.Music -e",
            "winget install --id=Nvidia.GeForceExperience -e",
            "winget install --id=Nvidia.Broadcast -e",
            "winget install --id=Nvidia.GeForceNow -e",
            "winget install --id=Nvidia.RTXVoice -e",
            "winget install --id=Wagnardsoft.DisplayDriverUninstaller -e",
            "winget install --id=TechPowerUp.NVCleanstall -e",
            "winget install --id=CPUID.CPU-Z -e",
            "winget install --id=CPUID.HWMonitor -e",
            "winget install --id=Guru3D.Afterburner -e",
            "winget install --id=FinalWire.AIDA64.Engineer -e",
            "winget install --id=FinalWire.AIDA64.Extreme -e",
            "winget install --id=Klocman.BulkCrapUninstaller -e",
            "winget install --id=Stardock.Fences -e",
            "winget install --id=TechPowerUp.GPU-Z -e",
            "winget install --id=Piriform.CCleaner -e",
            "winget install --id=Glarysoft.GlaryUtilities -e",
            "winget install --id=Rufus.Rufus -e",
            "winget install --id=AntibodySoftware.WizTree -e",
            "winget install --id OpenVPNTechnologies.OpenVPN -e",
            "winget install --id MullvadVPN.MullvadVPN -e",
            "winget install --id IVPN.IVPN -e",
            "winget install --id ExpressVPN.ExpressVPN -e",
            "winget install --id AirVPN.Eddie -e",
            "winget install --id VPNetwork.TorGuard -e",
            "winget install --id LightyearVPN.LightyearVPN -e",
            "winget install --id Mozilla.VPN -e",
            "winget install --id eVenture.HideMe -e",
            "winget install --id SURF.eduVPNClient -e",
            "winget install --id AdGuard.AdGuardVPN -e",
            "winget install --id AnchorFree.TouchVPN -e",
            "winget install --id tailscale.tailscale -e",
            "winget install --id SonicWALL.NetExtender -e",
            "winget install --id SparkLabs.Viscosity -e",
            "winget install --id PrivateInternetAccess.PrivateInternetAccess -e",
            "winget install --id LogMeIn.Hamachi -e",
            "winget install --id Cloudflare.Warp -e",
            "winget install --id Malwarebytes.Privacy -e",
            "winget install --id WireGuard.WireGuard -e",
            "winget install --id Surfshark.Surfshark -e",
        };
    }
}
